#!/bin/bash

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e
exec 2> >(logger --tag=dbus-system-bus --id=$$)

mkdir -p /run/dbus
dbus-uuidgen --ensure=/mnt/stateful/machine-id
/usr/bin/dbus-daemon --system --print-pid --print-address
