#!/bin/bash

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e
exec 2> >(logger --tag=mount-tracefs --id=$$)

DESTDIR="/sys/kernel/tracing"
mount -t tracefs tracefs "${DESTDIR}"
echo 0 > "${DESTDIR}/tracing_on"
