#!/bin/bash

# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e
exec 2> >(logger --tag=setup-cache-dir --id=$$)

USERNAME=chronos
CACHE_DIR="/home/${USERNAME}/.cache"

if [[ ! -d "${CACHE_DIR}" ]]; then
  mkdir "${CACHE_DIR}"
fi

# Written outside of the if statement to fix .cache directory that might be
# owned by root and doesn't have the correct permissions.
chown "${USERNAME}:${USERNAME}" "${CACHE_DIR}"
chmod 0755 "${CACHE_DIR}"
