#!/bin/bash

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e
exec 2> >(logger --tag=sommelier-wait --id=$$)

while [[ ! -S "/tmp/.X11-unix/X0" ]]; do
    sleep 0.5
done
