#Tabs not spaces, you moron :)

name: CI for netris:server

on:
    pull_request:
        paths:
            - "server.Dockerfile"
            - ".scripts/**"
            - ".github/workflows/server.yml"
    schedule:
        - cron: 0 0 * * * # At the end of everyday
    push:
        branches: [main]
        paths:
            - "server.Dockerfile"
            - ".scripts/**"
            - ".github/workflows/server.yml"
        tags:
            - v*.*.*
    release:
        types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nestriness/nestri
  BASE_TAG_PREFIX: server

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true
  
jobs:
    build-docker-pr:
        name: Build image on pr
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            -
              name: Checkout repo
              uses: actions/checkout@v4
            - 
              name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - 
              name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                file: server.Dockerfile
                context: ./
                push: false
                load: true
                tags: netris:server

    build-docker-main:
        name: Build image on merge to main
        if: ${{github.ref == 'refs/heads/main'}}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -
              name: Checkout repo
              uses: actions/checkout@v4
            - 
              name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GIT_MASTER_TOKEN }}
            - 
              name: Extract Container metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.BASE_TAG_PREFIX }}
                #
                #tag on release, and a nightly build for 'dev'
                tags: |
                  type=raw,value=nightly,enable={{is_default_branch}}
                  type=ref,event=tag
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
            - 
              name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                file: server.Dockerfile
                context: ./
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                
    build-docker-release:
        name: Build image on release
        if: ${{ github.event_name == 'release' }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -
              name: Checkout repo
              uses: actions/checkout@v4
            - 
              name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GIT_MASTER_TOKEN }}
            - 
              name: Extract Container metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.BASE_TAG_PREFIX }}
                #
                #tag on release, and a nightly build for 'dev'
                tags: |
                  type=raw,value=nightly,enable={{is_default_branch}}
                  type=ref,event=tag
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
            - 
              name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                file: server.Dockerfile
                context: ./
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}