# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

argv: "/etc/init.d/dbus-system-bus"
respawn: false
wait_for_exit: true
# TODO(davidriley): use_console is required for wait_for_exit, likely
# due to dbus-daemon --system not entirely daemonizing.
use_console: true
