# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

argv: "/etc/init.d/setup-cache-dir"
respawn: false
wait_for_exit: true
