# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# TODO(b/192026058): Work around unreadable traffic_class file.
argv: "/etc/init.d/fix-traffic-class"
respawn: false
