# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

argv: "/usr/sbin/tracebox"
argv: "traced"
argv: "--set-socket-permissions"
argv: "traced-producer:0660:traced-consumer:0660"
respawn: true
wait_for_exit: false
