# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

argv: "/usr/bin/launch_user_dbus_service.sh"
argv: "/usr/lib/xdg-desktop-portal-gtk"

respawn: true
wait_for_exit: false
